[package]
name = "verlet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.1", features = ["convert-glam022"] }
rand = "0.8.5"
rerun = "0.6.0"

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
